name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4
      with:
        path: main    
    - uses: actions/checkout@v2
    - name: Buildd the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
