name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main 
  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Buildd the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  login:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: kumar08401
        password: $Zaq1Xsw2
