name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main 
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build business-layer container
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: my-project/base
          context: business
          file: Dockerfile
  #build:
    #needs: checkout
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: Buildd the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  #login:
    #needs: build
    #runs-on: ubuntu-latest
    #steps:
    #- name: Login to Docker Hub
      #uses: docker/login-action@v3
      #with:
        #username: kumar08401
        #password: $Zaq1Xsw2
  #tag:
    #needs: login
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: tag Docker image
      #run: docker push . --file Dockerfile --tag my-image-name:$(date +%s)
      #run: docker tag my-image-name:$(date +%s) yourhubusername/verse_gapminder:my-image-name:$(date +%s)