 name: testingworkflow
 on:
  push:
    branches: [ main ]
 
 jobs:
   makefile:
    runs-on: ubuntu-latest
    steps:
      - name: makefile
        run: |
         echo "step1value=hello"
    outputs:
     output1: ${{ steps.step1.outputs.step1value }}
