name: testingworkflow
on:
 push:
   branches: [ main ]

jobs:
  makefile:
   runs-on: ubuntu-latest
   steps:
     - name: makefile
       run: |
        echo "savefile=testing" >> testing.txt
        ls
        cat ${{testing.txt}}
       
