name: variableandenv

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "demovaribale"
        default: "demostring"
        
env:
  registry: "docker.io"
  repository: "kumar08401"

jobs:
  demoenv:
    runs-on: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: reposiry update
        run: echo "${{env.registry}}/${{env.repository}}"
      #- name: context2
        #env:
          #github_context: github
          #run: echo ${{github_context}}
