name: variableandenv

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "demovaribale"
        default: "demostring"
        
env:
  registry: "docker.io"
  repository: "kumar08401"
jobs:
  job2:
      runs-on: ubuntu-latest
      
      outputs:
        output1: ${{ steps.step1.outputs.step1value }}
        output2: ${{ steps.step2.outputs.step2value }}
      
      steps:
        - name: Step 1
          id: step1
          # run: echo "::set-output name=step1value::hello"
          run: echo "step1value=hello"

        - name: Step 2
          id: step2
          # run: echo "::set-output name=step2value::world"
          run: echo "step2value=world"
    
  job3:
        runs-on: ubuntu-latest
        needs: job2
        steps:
          - run: echo ${{needs.job2.outputs.output1}}
