name: variableandenv

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: "demovaribale"
        default: "demostring"
        
env:
  registry: "docker.io"
  repository: "kumar08401"

jobs:
  demoenv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: reposiry update
        run: echo "${{env.registry}}/${{env.repository}}"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: | 
           echo "$GITHUB_CONTEXT"
      - name: namevar
        id: namevarid
        run: echo "name=kumar"
    outputs:
      output1: ${{steps.namevarid.name}}
  demoscanvar:
    runs-on: ubuntu-latest
    needs: demoenv 
    steps:
      - name: pulltheenvfromjobdemoenv
        run: echo ${{needs.demoenv.outputs.output1}}
