name: varsandenv

on: 
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: "repository"
env:
  registory: docker.io
  repository: kumar08401

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: export the value
        id: exportid
        run: echo "savevalue=kumar" >> $kumar
    outputs:
      output1: ${{steps.exportid.outputs.savevalue}}
